### ISSUE TITLE
ModuleNotFoundError: No module named 'model' i am getting this issue

### ISSUE THREAD

**Issue by ShriyashBPatil** [PSY222/Colorinsight#2]
PS F:\Shinde\Colorinsight> python -u "f:\Shinde\Colorinsight\facer\main.py"
Traceback (most recent call last):
  File "f:\Shinde\Colorinsight\facer\main.py", line 2, in <module>
    import functions as f
  File "f:\Shinde\Colorinsight\facer\functions.py", line 16, in <module>
    from model import BiSeNet
ModuleNotFoundError: No module named 'model'
PS F:\Shinde\Colorinsight>

**Comment by ShriyashBPatil** [comment]
PS F:\Shinde\Colorinsight> python -u "f:\Shinde\Colorinsight\facer\main.py"
Traceback (most recent call last):
  File "f:\Shinde\Colorinsight\facer\main.py", line 2, in <module>
    import functions as f
  File "f:\Shinde\Colorinsight\facer\functions.py", line 16, in <module>
    from model import BiSeNet
ImportError: cannot import name 'BiSeNet' from 'model' (f:\Shinde\Colorinsight\facer\model.py)
PS F:\Shinde\Colorinsight>

**Comment by Paopasatiht** [comment]
what is the step to train to get the model if the model file is confidential @PSY222

**Comment by trgthuhg** [comment]
me too
PS D:\Doan\Colorinsight\facer> python main.py
Traceback (most recent call last):
  File "D:\Doan\Colorinsight\facer\main.py", line 2, in <module>
    import functions as f
  File "D:\Doan\Colorinsight\facer\functions.py", line 16, in <module>
    from model import BiSeNet
